# Generated by Django 5.1.6 on 2025-03-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_assigned_to_alter_taskdetail_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In_Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15),
        ),
    ]
