# Generated by Django 5.1.6 on 2025-03-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskdetail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
