# Generated by Django 5.1.6 on 2025-03-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_project_description_taskdetail_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetail',
            name='assigned_to',
        ),
    ]
